/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PixRouteImport } from './routes/pix'
import { Route as ExtratoRouteImport } from './routes/extrato'
import { Route as ContaRouteImport } from './routes/conta'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AfiliadosRouteImport } from './routes/afiliados'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiPublicTelegramAuthRouteImport } from './routes/api/public/telegram/auth'

const PixRoute = PixRouteImport.update({
  id: '/pix',
  path: '/pix',
  getParentRoute: () => rootRouteImport,
} as any)
const ExtratoRoute = ExtratoRouteImport.update({
  id: '/extrato',
  path: '/extrato',
  getParentRoute: () => rootRouteImport,
} as any)
const ContaRoute = ContaRouteImport.update({
  id: '/conta',
  path: '/conta',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AfiliadosRoute = AfiliadosRouteImport.update({
  id: '/afiliados',
  path: '/afiliados',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicTelegramAuthRoute = ApiPublicTelegramAuthRouteImport.update({
  id: '/api/public/telegram/auth',
  path: '/api/public/telegram/auth',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/afiliados': typeof AfiliadosRoute
  '/auth': typeof AuthRoute
  '/conta': typeof ContaRoute
  '/extrato': typeof ExtratoRoute
  '/pix': typeof PixRoute
  '/api/public/telegram/auth': typeof ApiPublicTelegramAuthRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/afiliados': typeof AfiliadosRoute
  '/auth': typeof AuthRoute
  '/conta': typeof ContaRoute
  '/extrato': typeof ExtratoRoute
  '/pix': typeof PixRoute
  '/api/public/telegram/auth': typeof ApiPublicTelegramAuthRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/afiliados': typeof AfiliadosRoute
  '/auth': typeof AuthRoute
  '/conta': typeof ContaRoute
  '/extrato': typeof ExtratoRoute
  '/pix': typeof PixRoute
  '/api/public/telegram/auth': typeof ApiPublicTelegramAuthRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/afiliados'
    | '/auth'
    | '/conta'
    | '/extrato'
    | '/pix'
    | '/api/public/telegram/auth'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/afiliados'
    | '/auth'
    | '/conta'
    | '/extrato'
    | '/pix'
    | '/api/public/telegram/auth'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/afiliados'
    | '/auth'
    | '/conta'
    | '/extrato'
    | '/pix'
    | '/api/public/telegram/auth'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AfiliadosRoute: typeof AfiliadosRoute
  AuthRoute: typeof AuthRoute
  ContaRoute: typeof ContaRoute
  ExtratoRoute: typeof ExtratoRoute
  PixRoute: typeof PixRoute
  ApiPublicTelegramAuthRoute: typeof ApiPublicTelegramAuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/pix': {
      id: '/pix'
      path: '/pix'
      fullPath: '/pix'
      preLoaderRoute: typeof PixRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/extrato': {
      id: '/extrato'
      path: '/extrato'
      fullPath: '/extrato'
      preLoaderRoute: typeof ExtratoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conta': {
      id: '/conta'
      path: '/conta'
      fullPath: '/conta'
      preLoaderRoute: typeof ContaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/afiliados': {
      id: '/afiliados'
      path: '/afiliados'
      fullPath: '/afiliados'
      preLoaderRoute: typeof AfiliadosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/telegram/auth': {
      id: '/api/public/telegram/auth'
      path: '/api/public/telegram/auth'
      fullPath: '/api/public/telegram/auth'
      preLoaderRoute: typeof ApiPublicTelegramAuthRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AfiliadosRoute: AfiliadosRoute,
  AuthRoute: AuthRoute,
  ContaRoute: ContaRoute,
  ExtratoRoute: ExtratoRoute,
  PixRoute: PixRoute,
  ApiPublicTelegramAuthRoute: ApiPublicTelegramAuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
